Create 28_04_pgmeeting.md
ismrm-iberian/ismrm-iberian.github.io pull request #76
Opened 2021-04-28 13:56 UTC by ritagnunes

2021-04-28 14:48 UTC, eurunuela requested changes
@ritagnunes is this intended to be like a recap post?

2021-04-28 14:48 UTC, eurunuela commented on _posts/28_04_pgmeeting.md
> +author: teresa
```suggestion
author: rita
```

2021-04-28 19:52 UTC, ritagnunes commented
I have changed the title, so hopefully that should make it clearer.

2021-04-29 07:48 UTC, eurunuela approved these changes

2021-04-29 07:48 UTC, merged